# Generated by Django 2.0.9 on 2018-12-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(help_text='cm', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='pizzaApp.Pizza')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_variation', to='pizzaApp.PizzaSize')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pizzavariation',
            unique_together={('pizza', 'size')},
        ),
    ]
